### ISSUE TITLE
ExeTera Example Notebooks: end-to-end examples - HDG critical

### ISSUE THREAD

**Issue by atbenmurray** [KCL-BMEIS/ExeTera#105]

**Comment by ericspod** [comment]
Tutorial 1: create simple csv and schema and convert to hdf5 file, load file into ExeTera and poke a little 
Tutorial 2: load hdf5 file again, do query, visualization, etc. something simple on that data, sort dataset?
Tutorial 3: create second dataset, do sort or merge between datasets
Tutorial 4: generate large datasets, merge
