### ISSUE TITLE
ExeTera wiki: look for missing / incorrect content in the exetera wiki

### ISSUE THREAD

**Issue by atbenmurray** [KCL-BMEIS/ExeTera#175]

**Comment by csudre** [comment]
For instance in Intermediate examples, would be important to note from where to import the merge function by having  "from exetera.core.dataframe import DataFrame, merge"

**Comment by csudre** [comment]
Would also be interesting to know the options in create_dataframe to take the existing one if already present (otherwise error happens often when debugging) Apologies if I missed it
