### ISSUE TITLE
Import: optional default value for numeric fields for empty entries.

### ISSUE THREAD

**Issue by atbenmurray** [KCL-BMEIS/ExeTera#79]

**Comment by clyyuanzi-london** [comment]
There're two options I can think of to add default values for numeric fields:

(1) add default values in the schema

(2) add an argument in the command line. If so, any preference on the format?

**Comment by clyyuanzi-london** [comment]
What about the following format?
--default patient:(field_1, 'value_1'), (field_2, 'value_2'), assessment:(field_3, 'value')
