### ISSUE TITLE
Import: numeric field expanded import options

### ISSUE THREAD

**Issue by atbenmurray** [KCL-BMEIS/ExeTera#82]
Numeric fields should have an expanded set of options:
* Current behaviour
  * Numeric fields should allow for empty entries and entries that can be parsed correctly
  * Numeric fields generate a _valid field additional to the field itself indicating whether a given row is valid or not

New behaviours:
  * Validation:
    * Accept empty values (current behavior)
    * Strict
      * Expect all numbers to parse correctly or fail
    * Relaxed
      * Treat all casting failures as values to flag as invalid
 * Flag field
   * export flag field
   * don't export flag field (set to default value only)

Please also think about how to represent that in the schema.

Conversation from 18/03:
Here are all the combinations that I can think of:
 * no _valid field, fail on any non-numeric values (strict)
 * no _valid field, fail on any non-empty non-numeric values, write default value for empty numeric values (normal)
 * no _valid field, write default value for all non-numeric values (relaxed)
 * **no strict with _valid field**
 * _valid_field, fail on any non-empty non-numeric values, write default value for empty numeric values (normal)
 * _valid field, write default value for all non-numeric values (relaxed) - CURRENT MODE

**Comment by clyyuanzi-london** [comment]
Here is what I think of how the validation and flag field is presented in the schema:
"a_numeric_field": {
  "field_type": "numeric",
  "value_type": "uint16",
  "default": 100
  "validation_mode": "strict" (or "normal", "relaxed")
  "if_export_flag_field": True (False)
},

**Comment by atbenmurray** [comment]
"default" -> "invalid_value"
"validation_mode": "strict", "allow_empty", "relaxed" (allow_empty by default)
"create_flag_field": True, False (True by default)
"flag_field_name": string ("_valid" by default) (ignored if 'create_flag_field' is False)

What do you think of these?

**Comment by clyyuanzi-london** [comment]
Sounds good.
